version: 2

updates:
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily

  - directory: /
    package-ecosystem: npm
    schedule:
      interval: weekly
      day: monday
      time: 08:00
      timezone: America/New_York