# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301

[[redirects]]
  from = "/cloud"
  to = "/docs/production/k8s/"
  status = 301

[[redirects]]
  from = "/docs"
  to = "/docs/intro"
  status = 301

[[redirects]]
  from = "/docs/app-dev"
  to = "/docs/fundamentals/interface_driven_development"
  status = 301

