# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301

[[redirects]]
  from = "/cloud"
  to = "/docs/production/k8s/"
  status = 301

[[redirects]]
from = "/edge"
to = "/docs/production/lattice/ngs"
status = 301

[[redirects]]
  from = "/docs"
  to = "/docs/intro"
  status = 301

[[redirects]]
  from = "/docs/app-dev"
  to = "/docs/fundamentals/interface_driven_development"
  status = 301

[[redirects]]
  from = "/docs/app-dev/a2a"
  to = "/docs/fundamentals/actors/a2a"
  status = 301

[[redirects]]
  from = "/docs/app-dev/create-actor"
  to = "/docs/fundamentals/actors/create-actor/"
  status = 301

[[redirects]]
  from = "/docs/app-dev/create-actor/update"
  to = "/docs/fundamentals/actors/create-actor/run"
  status = 301

[[redirects]]
  from = "/docs/app-dev/create-provider"
  to = "/docs/fundamentals/capabilities/create-provider/"
  status = 301

[[redirects]]
  from = "/docs/app-dev/create-actor/generate"
  to = "/docs/fundamentals/actors/create-actor/generate"
  status = 301

[[redirects]]
  from = "/docs/app-dev/create-actor/run"
  to = "/docs/fundamentals/actors/create-actor/run"
  status = 301

[[redirects]]
  from = "/docs/app-dev/std-caps"
  to = "/docs/fundamentals/capabilities"
  status = 301

[[redirects]]
from = "/docs/app-dev/secure/clusterkeys"
to = "/docs/production/secure/clusterkeys#zero-trust-invocations"
status = 301

[[redirects]]
  from = "/docs/category/reference/host-runtime/capabilities"
  to = "/docs/fundamentals/capabilities"
  status = 301

[[redirects]]
  from = "/docs/category/reference/lattice"
  to = "/docs/production/lattice"
  status = 301

[[redirects]]
  from = "/docs/docs/getting-started"
  to = "/docs/installation"
  status = 301

[[redirects]]
  from = "/docs/getting-started"
  to = "/docs/installation"
  status = 301

[[redirects]]
  from = "/docs/overview/getting-started"
  to = "/docs/installation"
  status = 301

[[redirects]]
  from = "/docs/overview/installation"
  to = "/docs/installation"
  status = 301

[[redirects]]
  from = "/docs/overview/installation/install-with-docker"
  to = "/docs/installation?os=docker"
  status = 301

[[redirects]]
  from = "/docs/downloads"
  to = "/docs/installation"
  status = 301

[[redirects]]
  from = "/docs/faq"
  to = "/docs/reference/faq"
  status = 301

[[redirects]]
  from = "/docs/interfaces/codegen-toml"
  to = "/docs/hosts/abis/wasmbus/interfaces/codegen-toml"
  status = 301

[[redirects]]
  from = "/docs/interfaces/crates-io"
  to = "/docs/hosts/abis/wasmbus/interfaces/crates-io"
  status = 301

[[redirects]]
  from = "/docs/platform-builder"
  to = "/docs/installation"
  status = 301

[[redirects]]
  from = "/docs/platform-builder/docker"
  to = "/docs/installation?os=docker"
  status = 301

[[redirects]]
  from = "/docs/reference/alternate-install-methods/install-with-docker"
  to = "/docs/installation?os=docker"
  status = 301

[[redirects]]
from = "/docs/reference/host-runtime"
to = "/docs/category/host-runtimes"
status = 301

[[redirects]]
from = "/docs/reference/host-runtime/actors"
to = "/docs/hosts/abis/components/"
status = 301

[[redirects]]
from = "/docs/reference/host-runtime/security"
to = "/docs/hosts/security"
status = 301

[[redirects]]
from = "/docs/reference/custom/authorizers"
to = "/docs/production/secure/clusterkeys#zero-trust-invocations"
status = 301

[[redirects]]
from = "/docs/reference/lattice-protocols"
to = "/docs/hosts/lattice-protocols/"
status = 301

[[redirects]]
from = "/docs/reference/lattice-protocols/control-interface"
to = "/docs/hosts/lattice-protocols/control-interface"
status = 301

[[redirects]]
from = "/docs/reference/lattice/js_leaf"
to = "/docs/production/lattice/js_leaf"
status = 301

[[redirects]]
from = "/docs/reference/lattice/leaf-nodes"
to = "/docs/production/lattice/leaf-nodes"
status = 301

[[redirects]]
from = "/docs/reference/lattice/security-patterns"
to = "/docs/production/lattice/security-patterns"
status = 301

[[redirects]]
from = "/docs/reference/wasmbus"
to = "/hosts/abis/wasmbus/"
status = 301

[[redirects]]
from = "/docs/releases"
to = "/docs/reference/official-oci/"
status = 301

[[redirects]]
from = "/about"
to = "/"
status = 301
