name: Create Community Meeting Agenda
on:
  workflow_dispatch:
    inputs:
      date:
        description: "Date of next community meeting, in the form of YYYY-MM-DD"
        required: true
        type: string
      livestream_url:
        description: "URL of YouTube livestream for community meeting"
        required: true
        type: string
jobs:
  create_agenda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Community Agenda
        run: |
          bash agenda.sh ${{ inputs.date }} ${{ inputs.livestream_url }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: added community meeting agenda for ${{ inputs.date }}
          title: Community Agenda ${{ inputs.date }}
          body: This is the community meeting agenda for ${{ inputs.date }}. Agenda items are forthcoming because bleep bloop I am a bot.
          branch: community/${{ inputs.date }}
          signoff: true
