name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: docusaurus-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/ci_build.yml

  ci-check:
    needs: [build]
    if: ${{ always() }}
    uses: ./.github/workflows/workflow_check.yml
    with:
      pass-condition: ${{ contains(needs.*.result, 'failure') == false }}
