name: 'woke'
on:
  pull_request:

jobs:
  woke:
    name: Run woke
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.18 

      - name: Install woke
        run: |
          go install github.com/get-woke/woke@v0.19.0

      - name: Run woke
        run: |
          woke -c .woke.yaml --exit-1-on-failure