name: simple-check

on:
  workflow_call:
    inputs:
      pass-condition:
        type: boolean
        description: 'The condition to check'
        required: true
      fail-job-on-condition:
        description: 'Whether to fail the job if the condition is true'
        type: boolean
        required: false
        default: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Condition
        shell: bash
        run: |
          # Check the condition
          if [[ "${{ inputs.pass-condition }}" == 'true' ]]; then
            echo "Condition is true"
            echo "RESULT=success" >> $GITHUB_ENV
          else
            echo "Condition is false"
            echo "RESULT=failure" >> $GITHUB_ENV
          fi
      - name: Job Result
        id: result
        shell: bash
        if: ${{ inputs.fail-job-on-condition }}
        run: |
          # Set the output
          if [[ $RESULT == 'failure' ]]; then
            echo "::error ::Condition failed"
            exit 1
          else
            exit 0
          fi